#adapted from example in docker documentation
version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    user: 1000:1000 # For Linux users
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
