#adapted from example in docker documentation
version: '3.9'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
    #  ports:
    #     - 8000:8000
    user: 1001:1002
    #user: 1000:1000 # For Linux users
    #command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    working_dir: /code/mysite
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application

  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   volumes:
  #     - ./mysite/static/:/static
  #   depends_on:
  #     - web
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - web:web

  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
     - web
    links:
     - web:web
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - $PWD/Caddyfile:/etc/caddy/Caddyfile
     - $PWD/mysite/static:/srv/static/
   #  - $PWD/mysite/myapp/static:/srv/wasm/
     - caddy_data:/data
     - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: