# Generated by Django 4.0.2 on 2022-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
