# Generated by Django 4.0.2 on 2022-03-21 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_questionmodel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
