# Generated by Django 4.0.2 on 2022-03-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_answermodel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='image_description',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
